### ISSUE TITLE
Doesn't work on macOS 10.12.2

### ISSUE THREAD

**Issue by awwcmon** [teored90/nobootsound#13]

**Comment by matteoacrossi** [comment]
Dear @letjinxgo,
are you using headphones or other audio devices while rebooting? If so, can you try rebooting with all external sound devices unplugged?

**Comment by skywatcher2** [comment]
This is what I get on my OS 10.12.5:

Last login: Sun May 28 18:01:25 on ttys000
Yaacovs-iMac:~ yaacov$ cd/Desktop/nobootsound-master
-bash: cd/Desktop/nobootsound-master: No such file or directory
Yaacovs-iMac:~ yaacov$ sudo sh install.sh
Password:
sh: install.sh: No such file or directory
Yaacovs-iMac:~ yaacov$

**Comment by matteoacrossi** [comment]
You are trying to enter a directory that doesn’t exist. Are you sure that you downloaded the script into Desktop/nobootsound-master?

**Comment by ColdBlast** [comment]
You might find [the Wiki on this project](https://github.com/teored90/nobootsound/wiki), and the links provided therein, to be helpful.  (They helped me when I ran into problems!)  The installation folder often downloads as a ZIP (compressed) file, and you have to expand it before following the installation steps.  Just double-clicking on it (if the name ends in .zip) should do the trick.

**Comment by skywatcher2** [comment]
Well, yes, I should have verified that I had the unzipped folder sitting on my Desktop ready to go. Nevertheless, it was a no go. So I just finished hacking around with Terminal and the files and this is what I had to do to succeed in getting the startup sound muted.

First, drag the install.sh file and both of the Unix files out of the folder and onto the Desktop:

<img width="315" alt="screengrab" src="https://cloud.githubusercontent.com/assets/26773978/26566930/e5d07d34-44ab-11e7-8241-87ac53c1b9b4.png">

Then type: sudo Desktop/install.sh

This what happens next:
Last login: Mon May 29 20:02:31 on console
Yaacovs-iMac:~ yaacov$ sudo Desktop/install.sh
Password:
Copying files...
Registering hooks...
Done!
Yaacovs-iMac:~ yaacov$

Hope this helps. Maybe someone can explain why and how. All the Best.
iMac 17,1 macOS Sierra 10.12.5

**Comment by ColdBlast** [comment]
I'm guessing the problem was actually the leading / before desktop in
`cd/Desktop/nobootsound-master`
I believe 
`cd Desktop/nobootsound-master`
or, better, 
`cd ~/desktop/nobootsound-master`
would have worked.  But I come from the DOS world so I'm not 100% confident.  I did just try these on my own system and got "no such file or directory" with the leading / in place.  (I think this is because Desktop is a subfolder of your home folder, not a folder in your root directory, for those that means something to.)

Sorry I didn't catch that before.

**Comment by matteoacrossi** [comment]
Sorry, I didn't read the commands carefully. If you did type in

    cd/Desktop/nobootsound-master

then it definitely gives you an error because there is no space between cd and the path. Even with a space, the command `cd /Desktop/nobootsound-master` would try to look for a Desktop directory at the root of the file system, while the Desktop directory is in the user home directory. The correct command would be

    cd ~/desktop/nobootsound-master

Of course, after extracting the zip file.
